[database]
user = "postgres.rxtcigbzpbppqianbdcn"
password = "chaimaafennyn"
host = "aws-0-eu-west-3.pooler.supabase.com"
port = "6543"
dbname = "postgres"


[credentials]
users = [
  {username = "admin", password = "admin123", name = "Admin"},
  {username = "chaima", password = "1234", name = "Chaima Fennyn"}
]

[cookie]
expiry_days = 1
key = "projetStage"
name = "auth_cookie"

