[credentials]
usernames = [
  {username = "admin", password = "pbkdf2:sha256:260000$...", name = "Admin", email = "admin@example.com"}
]

[cookie]
expiry_days = 30
key = "some_signature_key"
name = "some_cookie_name"

[preauthorized]
emails = ["admin@example.com"]
